name: kiraya
description: A rent management application.
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  url_launcher: ^6.2.2
  # Navigation & UI
  google_nav_bar: ^5.0.6
  animations: ^2.0.8
  # Dashboard
  fl_chart: ^0.65.0
  countup: ^0.1.4
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  # Image Picker & Management
  image_picker: ^1.0.5
  # Utils
  collection: ^1.18.0
  flutter_layout_grid: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^2.4.8
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/icon.jpg
    - assets/images/google_logo.png
